---
jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up cache for Gentoo Prefix
        id: gentoo-prefix-cache
        uses: actions/cache@v3
        with:
          key: gentoo-prefix
          path: ${{ github.workspace }}/gentoo
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget curl
      - name: Bootstrap Gentoo Prefix
        if: steps.gentoo-prefix-cache.outputs.cache-hit != 'true'
        run: |
          wget -O bootstrap-prefix.sh \
            https://gitweb.gentoo.org/repo/proj/prefix.git/plain/scripts/bootstrap-prefix.sh
          chmod +x bootstrap-prefix.sh
          export LATEST_TREE_YES=1 EMERGE_DEFAULT_OPTS="--jobs 1 --quiet-build=y" ACCEPT_KEYWORDS="~amd64" ACCEPT_LICENSE="*" FEATURES="clean-logs"
          ./bootstrap-prefix.sh ${{ github.workspace }}/gentoo noninteractive
          source ${{ github.workspace }}/gentoo/etc/profile
          emerge --ask=n dev-util/pkgcheck
      - name: Run pkgcheck on changed content
        run: |
          source ${{ github.workspace }}/gentoo/etc/profile
          pkgcheck scan --net --commits master
name: pkgcheck
'on':
  pull_request:
    branches:
      - master
