---
jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up cache for Gentoo Prefix
        uses: actions/cache@v3
        with:
          fail-on-cache-miss: true
          key: gentoo-prefix
          path: ${{ github.workspace }}/gentoo
      - name: Run pkgcheck ci
        run: |
          source ${{ github.workspace }}/gentoo/etc/profile
          git remote set-head origin -a
          pkgcheck ci --debug --net --commits origin/master --failures failures.json \
            --exit error,warning,style,info
      - name: Upload pkgcheck failures file
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: pkgcheck-failures
          path: failures.json
name: pkgcheck
'on':
  pull_request:
    branches:
      - master
