---
jobs:
  refresh-gentoo-prefix:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEY: gentoo-prefix
        name: Delete existing cache
        run: |
          curl -fsSL -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${GH_REPO}/actions/caches?key=${KEY}"
      - id: prefix-cache
        name: Initialize cache path
        uses: actions/cache@v3
        with:
          key: gentoo-prefix
          path: ${{ github.workspace }}/gentoo
      - name: Bootstrap Gentoo Prefix
        run: bash ./scripts/ci-bootstrap-gentoo-prefix.sh "${{ github.workspace }}"
      - name: Cache Gentoo Prefix
        uses: actions/cache/save@v3
        with:
          key: gentoo-prefix
          path: ${{ github.workspace }}/gentoo
name: Refresh Gentoo Prefix Cache
'on':
  schedule:
    - cron: '0 0 1 * *'
